### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by daofeng2015** [he0119/smart-home-flutter#21]
![QQ截图20200316215529](https://user-images.githubusercontent.com/14891398/76765148-e620f700-67d0-11ea-8e75-c2d06079fd96.png)
最新的代码 sdk版本是 flutter_windows_v1.12.13+hotfix.8-stable 还有 依赖  intl: ^0.16.1应该是0.16.0

**Comment by he0119** [comment]
啊，因为我需要编译成网页所以用的 `dev` 频道  `1.14.6` 版本的。🤣
```
PS C:\Users\hmy01> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.18363.719], locale zh-CN)
```

**Comment by he0119** [comment]
如果你需要编译正式版 `APK` 的话，需要根据 [文档](https://flutter.dev/docs/deployment/android) 指示，创建签名。
并且我通过 `main_dev.dart` 和 `main_prod.dart` 两个文件将测试和正式环境的配置分离开了。
你需要通过运行 `flutter build apk -t .\lib\main_prod.dart` 来编译。

**Comment by daofeng2015** [comment]
> 如果你需要编译正式版 `APK` 的话，需要根据 [文档](https://flutter.dev/docs/deployment/android) 指示，创建签名。
> 并且我通过 `main_dev.dart` 和 `main_prod.dart` 两个文件将测试和正式环境的配置分离开了。
> 你需要通过运行 `flutter build apk -t .\lib\main_prod.dart` 来编译。

ok,,,,你readme没写,我也不知道啊..

**Comment by he0119** [comment]
我其实也没想过有人看🤣

**Comment by he0119** [comment]
我简单的写了一个 `readme`，你看看还有没有什么地方没有提到。

**Comment by daofeng2015** [comment]
> 我简单的写了一个 `readme`，你看看还有没有什么地方没有提到。

那个签名的链接换为 https://flutterchina.club/android-release/

**Comment by he0119** [comment]
我相信大家的英文水平😉

**Comment by daofeng2015** [comment]
> 我相信大家的英文水平😉

.
.fuck。。又编译错误了...等会发截图,我重启下电脑...

**Comment by daofeng2015** [comment]
> 我相信大家的英文水平😉

![QQ截图20200316230010](https://user-images.githubusercontent.com/14891398/76771190-eec9fb00-67d9-11ea-9bdc-e7d383d302d5.png)

**Comment by he0119** [comment]
看起来是你的签名没有弄好。 `Keystore file not set for signing config release`
在 `android` 目录下应该有一个 `key.properties` 文件，内容如下
```
storePassword=<password from previous step>
keyPassword=<password from previous step>
keyAlias=key
storeFile=<location of the key store file, such as /Users/<user name>/key.jks>
```
