### ISSUE TITLE
有测试账号和密码吗

### ISSUE THREAD

**Issue by hnyer** [he0119/smart-home-flutter#81]
https://smart-test.hehome.xyz/graphql  
登陆这个网站 貌似要账号和密码，

**Comment by he0119** [comment]
是的
账号是 test
密码 12345678
我主要也是测试用，服务器可能会不在线。

**Comment by hnyer** [comment]
> 是的
> 账号是 test
> 密码 12345678
> 我主要也是测试用，服务器可能会不在线。



好的，我是想登陆进去看看 APP功能和效果

**Comment by he0119** [comment]
哈哈哈哈哈哈，很菜的，我也是写着玩玩

**Comment by he0119** [comment]
如果没有其他问题，我就关掉了。
